# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :beta do

   

    appcenter_upload(
      api_token: "a9edd130c4772fe97a475854f54a29391b978587",
      owner_name: "warintorn.yangkijkarn-scb.co.th",
      #owner_type: "user", # Default is user - set to organization for appcenter organizations
      app_name: "Testing-Distributed",
      file: "./app/build/outputs/apk/release/app-release.apk",
      notify_testers: true # Set to false if you don't want to notify testers of your new release (default: `false`)
    )
  end

end
